apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: backend-app
        image: chewi9/springuma:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080